config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
get 'home/about'
get 'home/generator'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  def generator
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class = 'navbar-header'>

      <button type = 'button' class= 'navbar-toggle collapsed' data-toggle= 'collapse'
      data-target= '#bs-example-navbar-collapse-1'>
      <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', home_about_path %></li>
            <li><%= link_to 'Generator', home_generator_path %></li>


          </ul>



</div>




</div>
</nav>

app/views/home/about.html.erb
<h1>About the site</h1>

app/views/home/generator.html.erb
<p>GENERATOR</p>

app/views/home/index.html.erb
<div class = 'jumbotron'>
  <h1>Generate Reports</h1>

<p> Hate it when you are surprised that reports are due in two days?
  How long does it take?
  Four hours? Lets do them together...
  120 students in about 30 mins the first time...
  Next time, MUCH less!
</p>

<p><%= link_to 'Check Out the video', home_about_path, class:"btn btn-primary btn-lg" %>
<%= link_to 'Try it out!',home_generator_path, class:"btn btn-success btn-lg" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReportApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'home/header' %>

  <div class="container">

    <% flash.each do |name, message| %>
    <%= content_tag(:div, msg, class:"alert alert-info") %>
    <% end %>
<%= yield %>
</div>


</body>
</html>